### ISSUE TITLE
[Plugin] Add one pull tapes tasks per app/lib flavor

### ISSUE THREAD

**Issue by felipecsl** [airbnb/okreplay#21]

**Comment by niranjani23** [comment]
I don't see the push task.

**Comment by felipecsl** [comment]
The push task has since been removed. There is only `pullOkReplayTapes` and `clearOkReplayTapes`

**Comment by adelnizamutdinov** [comment]
for some reason pulling doesn't work for me at all =/

**Comment by felipecsl** [comment]
@adelnizamutdinov did you see the task running? maybe try running gradle with `--info` to see if there are any errors
