### ISSUE TITLE
Wrong Maven coordinates and download link in readme

### ISSUE THREAD

**Issue by lfielke** [airbnb/okreplay#36]
It looks like the Download section in the readme has a couple of typos.

Looking at http://search.maven.org/#search%7Cga%7C1%7Ccom.airbnb.okreplay I can see these artifacts:
* `noop`
* `junit`
* `espresso`
* `okreplay`
* `gradle-plugin`

In the readme, the link to "Download the latest JAR" points at https://search.maven.org/remote_content?g=com.airbnb.okreplay&a=core&v=LATEST but it appears the artifact is now `okreplay` instead of `core`.

The provided Maven coordinates also don't work for me, eg the Maven example has artifactId `okreplay-core`, but it seems to be published as `okreplay`, as above.

Likewise the 2nd and 3rd lines in the Gradle example should have the leading `okreplay-` removed by the looks of things.

**Comment by felipecsl** [comment]
Thank you, fixed it!

**Comment by lfielke** [comment]
Thanks for jumping on this so quickly.

I can see the Maven coordinates are fixed, but the download JAR link still 404s for me (it wasn't changed in the pull request).

**Comment by felipecsl** [comment]
Hmm the maven coordinates look correct to me now, they were indeed changed on #37.
Did you see the difff?

**Comment by lfielke** [comment]
I can see the diff, but the download link is not changed in it. Just to clarify, I'm talking about the link with text "the latest JAR" that points at https://search.maven.org/remote_content?g=com.airbnb.okreplay&a=core&v=LATEST

This is the one on line 131 of readme.md.

**Comment by felipecsl** [comment]
Found it, thanks @lfielke!
