### ISSUE TITLE
OkReplay Annotation is too strict

### ISSUE THREAD

**Issue by christopherperry** [airbnb/okreplay#50]
It takes an array of `MatchRules`. It should be an array of `MatchRule` so we can pass in custom rules and not one from the default set.

**Comment by christopherperry** [comment]
I think it's also a good idea to allow the use of multiple tapes, vs just a single tape.

**Comment by felipecsl** [comment]
FWIW you can set custom match rules via `OkReplayConfig`, but agreed, the annotation is too strict. We can replace it with `MatchRule` instead.

**Comment by felipecsl** [comment]
Ah, forgot why that's the case: Unfortunately annotation fields have to be compile time constants, that is interfaces are not allowed (https://kotlinlang.org/docs/reference/annotations.html):
```
Allowed parameter types are:

types that correspond to Java primitive types (Int, Long etc.);
strings;
classes (Foo::class);
enums;
other annotations;
arrays of the types listed above.
```
Bummer 😢

**Comment by christopherperry** [comment]
`classes (Foo::class);` would work given Foo is an implementation of `MatchRule`. This should be doable.

**Comment by felipecsl** [comment]
I think by "classes", it means the `Class` class, not an instance of any class:
![image](https://user-images.githubusercontent.com/190648/27650080-af699bb4-5be8-11e7-8efd-f99a64fd4f01.png)
![image](https://user-images.githubusercontent.com/190648/27650095-baec2592-5be8-11e7-9898-aa43e5358da5.png)
