### ISSUE TITLE
Yaml file was not generated after test run.

### ISSUE THREAD

**Issue by niranjani23** [airbnb/okreplay#55]
I added all the dependencies and annotations as mentioned in the wiki to my espresso test. 
Here are the steps I followed to run a single test via command line: 
1. Install apk via gradlew: 
./gradlew install<Flavor>

2. Install test apk via gradlew:
./gradlew install<Flavor>AndroidTest

3. Run single test via adb:
./adb shell am instrument -w -r -e class com.xxx.Tests#testFunction com.xxx.test/com.xxx.base.AndroidInstrumentationTestRunner

The test runs successfully but I don't see the Yaml file being generated under androidTest->assets -> tapes. Any thoughts?

**Comment by felipecsl** [comment]
@niranjani23 you need to use gradle in order for the yaml files to be created.
just replace step 3 with `./gradlew connectedCheck`
This will make sure that the OkReplay plugin pull the yaml files from the device before the test finishes.

**Comment by niranjani23** [comment]
Running ./gradlew connectedCheck throws StackOverflowError for me. I even tried using the multidex dependencies but in vain. Any other way to trigger the OkReplay plugin?

**Comment by felipecsl** [comment]
you can manually pull the tapes by running `./gradlew pullOkReplayTapes`. Does that work?

**Comment by niranjani23** [comment]
Just to clarify: I can run the above 3 steps and then manually run the ./gradlew pullOkReplayTapes ? 
I did the above but I only notice that the assets folder is being created with an empty tapes folder. I don't see the yaml files.

**Comment by felipecsl** [comment]
this could mean that no tape files were created then. You can confirm by running `adb shell`
and cd'ing into `/sdcard/okreplay/tapes` to see if the directory exists or if there's anything in there.
are you running with `TapeMode.READ_WRITE` or `WRITE_ONLY`? Otherwise nothing will be written

**Comment by niranjani23** [comment]
After cd'ing into /sdcard/okreplay/tapes, I do notice that the directory exists but don't see any tape files. 
I do have TapeMode.READ_WRITE only. Would running ./gradlew connectedAndroidTest instead of ./gradlew connectedCheck trigger OkReplay plugin to generate the tape files?

**Comment by felipecsl** [comment]
`connectedCheck` should trigger `connectedAndroidTest`, so it doesn't matter which one you run.
I'd recommend looking at logcat to see what's going on. You should see logs like:
```
I/TestRunner(9061): started: found @OkReplay annotation on 'methodName(com.example.TestClassName)'
```
and
```
OkReplayInterceptor: Recording request http://example.com/...
```
Also try debugging and putting a breakpoint on `OkReplayInterceptor` to see if it's being invoked at all

**Comment by niranjani23** [comment]
I do see the I/RecorderRule: found @OkReplay annotation on 'methodName(com.example.TestClassName)' but I don't see the OkReplayInterceptor being triggered.

**Comment by felipecsl** [comment]
yeah so most likely your interceptor is not set up correctly.
make sure that the interceptor instance that you passed to the `OkReplayConfig.Builder` is the same that you added to the `OkHttpClient.Builder`
