### ISSUE TITLE
Problems running okreplay gradle plugin with Android Studio 3.1

### ISSUE THREAD

**Issue by slavasav** [airbnb/okreplay#66]
Having problems running the Android Studio 3.1 Canary 7 and 8 build. So gradle version is 4.4, gradle plugin is com.android.tools.build:gradle:3.1.0-alpha07.
If running with "apply plugin: 'okreplay" the gradle configuration stage gets stuck on connecting to adb (even if no simulator or devices are running), the log prints this in an eternal loop:

[DeviceMonitor]: Unable to open connection to: localhost/10.128.0.62:5037, due to: java.net.ConnectException: Operation timed out
[DeviceMonitor]: Connection attempts: 1

Everything runs fine when disabling the okreplay plugin.

Also tried clearing gradle caches and killing adb. The gradle debug log does not show any more information than the error above.

**Comment by slavasav** [comment]
This was my problem with adb, the ipv4 loopback has not been present in localhosts, only the ipv6.

**Comment by qiixiao** [comment]
@slavasav How do you fix it?

**Comment by slavasav** [comment]
I replaced this:
`::1             localhost`
in /etc/hosts with this:
`127.0.0.1 localhost`

**Comment by qiixiao** [comment]
@slavasav me to, My mistake

**Comment by UnnikrishnanBhargavakurup** [comment]
Still not connecting getting the following message

	```
Could not open Selected VM debug port (8700). Make sure you do not have another instance of DDMS or of the eclipse plugin running. If it's being used by something else, choose a new port number in the preferences.
Unable to open connection to: localhost/17.253.38.253:5037, due to: java.net.ConnectException: Operation timed out
```

**Comment by psousa50** [comment]
I'm having the same exact problem as @UnnikrishnanBhargavakurup . Any news on this?
