### ISSUE TITLE
READ_ONLY mode is actually not read-only

### ISSUE THREAD

**Issue by tmtrademarked** [airbnb/okreplay#69]
We found a strange failure in one of our tests recently. For some reason, our test failed when trying to connect to a server. That's unexpected, because the test was running in TapeMode READ_ONLY.

It turns out with the current implementation of OkReplayInterceptor, a read-only tape will *still* make the server call if a match is not found on a particular tape. This is bad, because it introduces flakiness if the server is non-responsive. That's not what we want in a READ_ONLY mode.

https://github.com/airbnb/okreplay/pull/68 should address this, if desired.

**Comment by felipecsl** [comment]
Closed by #68

**Comment by tmtrademarked** [comment]
Awesome - thanks, @felipecsl ! Is this available in a snapshot or a new release yet?

**Comment by felipecsl** [comment]
Yes, 1.5.0-SNAPSHOT is available now!

**Comment by Tapchicoma** [comment]
Really would love to have a next release with this feature, using `SNAPSHOT` version on main branch is not a best practice :(
