### ISSUE TITLE
Java library

### ISSUE THREAD

**Issue by jd-alexander** [airbnb/okreplay#72]
Can this project be utilized in a Java library? The API seems heavily Android-based.

**Comment by felipecsl** [comment]
It can, you can crab just the `okreplay-junit` module, it should work fine.

**Comment by jd-alexander** [comment]
Okay understood. So I would have to make the `RecorderRule` public and then create that rule within  JUnit before the @OkReplay annotation would chip in right? Also how do I create a Tape?

**Comment by quiqua** [comment]
If I don't use JUnit for testing but Spek instead  (https://github.com/spekframework/spek/) - is there a core API I can use without all the Rule things JUnit brings?

Basically I want to:
- add the intercepter
- in a before block tell the intercepter to record / replay
