### ISSUE TITLE
Possible to get a new release cut?

### ISSUE THREAD

**Issue by tmtrademarked** [airbnb/okreplay#87]
It looks like there's some new work going into this library, which is great to see. But I wanted to see if we could get a timeline from the maintainers on a possible release. Continuing to depend on a snapshot version is no longer tenable for us, and we'd like to use a stable version if possible. If there are no plans for a release any time soon, it would be nice to know that so we can evaluate our options.

Thank you for all the work you've put into this library - it's a wonderful contribution to the Android ecosystem and much appreciated by those of use who use it.

**Comment by felipecsl** [comment]
Thanks for your kind feedback! I think we can probably get a new version out since it's been over an year since v1.4.0 has been released and we got a handful of changes since then.
I can prepare a v1.5.0, @rossbacher sounds good to you?

**Comment by shareme** [comment]
make sure it works under 5.2.1 gradle as current version does not

**Comment by pestrada** [comment]
Any news on 1.5.0 ?

**Comment by tmtrademarked** [comment]
Just wanted to follow up here to see if there was any traction on getting a 1.5.0 release. If the issue is technical maintenance, would it be possible to post a list somewhere of the blockers? It's possible those of us who use this library could help resolve some of the issues if we had visibility into what needs doing.

**Comment by felipecsl** [comment]
we can do it after #92 is merged

**Comment by felipecsl** [comment]
Version 1.5.0 has been released for da2789cc6590a716c469ccee3a801b83802f22a3
